// Generated by CoffeeScript 2.3.1
(function() {
  var assert, dependence, test;

  assert = require('assert');

  ({test} = require('ava'));

  dependence = require('../lib/dependence');

  test('vue', async function(t) {
    var vuejs;
    vuejs = (await dependence.vue());
    return t.true(vuejs.includes('Vue.js v2.5.17-beta.0'));
  });

  test('vue_json_pretty', async function(t) {
    var _vue_json_pretty;
    _vue_json_pretty = (await dependence.vue_json_pretty());
    return t.true(_vue_json_pretty.includes('name:"vue-json-pretty"'));
  });

  test('htmlTemplate', async function(t) {
    var _htmlTemplate;
    _htmlTemplate = (await dependence.htmlTemplate());
    t.true(_htmlTemplate.includes('<!DOCTYPE html>'));
    return t.true(_htmlTemplate.includes('VueJsonPretty: VueJsonPretty.default'));
  });

}).call(this);
