env:
  global:
    - CC_TEST_REPORTER_ID={ID}

language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - nyc --reporter=lcov ava
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
