// Generated by CoffeeScript 2.3.1
(function() {
  var _, fs, path, readFile, util;

  _ = require('lodash');

  util = require('util');

  fs = require('fs');

  path = require('path');

  readFile = util.promisify(fs.readFile);

  module.exports = {
    htmlTemplate: function() {
      return new Promise(function(resolve, reject) {
        return readFile(path.join(__dirname, '..', 'template/basic.html'), 'utf-8').then(resolve).catch(reject);
      });
    },
    vue: function() {
      return new Promise(function(resolve, reject) {
        return readFile(path.join(__dirname, '..', 'dependence/vue.min.js'), 'utf-8').then(resolve).catch(reject);
      });
    },
    vue_json_pretty: function() {
      return new Promise(function(resolve, reject) {
        return readFile(path.join(__dirname, '..', 'dependence/vue-json-pretty.js'), 'utf-8').then(resolve).catch(reject);
      });
    },
    logo: function() {
      return new Promise(function(resolve, reject) {
        return readFile(path.join(__dirname, '..', 'image/strfy_logo3.svg'), 'utf-8').then(resolve).catch(reject);
      });
    }
  };

}).call(this);
