// Generated by CoffeeScript 2.3.1
(function() {
  var fs, opn, util;

  util = require('util');

  fs = require('fs');

  opn = require('opn');

  module.exports = {
    writeFile: util.promisify(fs.writeFile),
    opn: opn
  };

}).call(this);
