// Generated by CoffeeScript 2.3.1
(function() {
  var fs, opn;

  fs = require('fs');

  opn = require('opn');

  module.exports = {
    writeFile: function(filePath, data) {
      return new Promise(function(resolve, reject) {
        return fs.writeFile(filePath, data, function(err) {
          if (err) {
            reject(err);
          }
          return resolve();
        });
      });
    },
    readFile: function(filePath, opt) {
      return new Promise(function(resolve, reject) {
        return fs.readFile(filePath, opt, function(err, data) {
          if (err) {
            reject(err);
          }
          return resolve(data);
        });
      });
    },
    opn: opn
  };

}).call(this);
